### ISSUE TITLE
AWS Billing entities (to use CloudWatch in consolidated billing account)

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/zmon-entity-adapter#1]
``` yaml
id: aws-bill-stups[aws:123456789012:eu-west-1]
type: aws_billing
team: myteam
account_alias: example-myteam
billing_id: '999956789012'
infrastructure_account: aws:123456789012
```
